org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true

#Mod Info
mod_version = 0.0.1
minecraft_version = 1.21.1

mod_id = lobotomycorp
mod_name = LobotomyCorp
mod_author = Yang429
mod_license = MIT License
mod_description = A mod with a lobotomy corp's abnormalIties and E.G.O.A mod with a lobotomy corp's abnormalIties and E.G.O.

# NeoForge
# https://neoforged.net/
neo_version=21.1.230

# Mappings
# https://parchmentmc.org/docs/getting-started
#
# parchment_minecraft_version being set to "same" will use minecraft_version
# parchment_version set to "none" will disable parchment mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17